{
 "title": "Historical Position of the Turtle  Dashboard Copy",
 "description": "X Y Position of the Turtle 1 with linear velocity >1",
 "time": { "from": "2025-02-18T14:17:35.175Z", "to": "2025-02-18T14:17:55.257Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Historical Position of the Turtle1 Dashboard",
   "type": "timeseries",
   "description": "X, Y position with linear velocity >1  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select (a.compound->>'x')::numeric as X,  (a.compound->>'y')::numeric as Y, a.ts as Timestamp\nfrom \n\"attributes\" a \nwhere a.entityid ='urn:ngsi-ld:robot:1' \nand a.id like '%/pose' \nand (a.compound ->> 'linear_velocity')::numeric >1\nand (a.compound->>'turtle_id') ='1'\nand a.ts > '2025-02-16T00:00:00'"
    }
   ]
  },
  {
   "title": "Historical Position of the Turtle2 Dashboard",
   "type": "timeseries",
   "description": "X, y Position with linear velocity >1",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select (a.compound->>'x')::numeric as X,  (a.compound->>'y')::numeric as Y, a.ts as Timestamp\nfrom \n\"attributes\" a \nwhere a.entityid ='urn:ngsi-ld:robot:1' \nand a.id like '%/pose' \nand (a.compound ->> 'linear_velocity')::numeric >1\nand (a.compound->>'turtle_id') ='2'\nand a.ts > '2025-02-16T00:00:00'"
    }
   ]
  },
  {
   "title": "Historical Position of the Turtle3 Dashboard",
   "type": "timeseries",
   "description": "X, Y Position with linear velocity >1",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select (a.compound->>'x')::numeric as X,  (a.compound->>'y')::numeric as Y, a.ts as Timestamp\nfrom \n\"attributes\" a \nwhere a.entityid ='urn:ngsi-ld:robot:1' \nand a.id like '%/pose' \nand (a.compound ->> 'linear_velocity')::numeric >1\nand (a.compound->>'turtle_id') ='3'\nand a.ts > '2025-02-16T00:00:00'"
    }
   ]
  }
 ]
}