{
 "title": "OPCUA _Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Current Speed  - OPOCUA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (a.compound->>'@value')::INTEGER AS \"Current Speed\", a.ts AS Time\r\nFROM attributes a\r\nwhere a.id like '%/CurrentSpeed'"
    }
   ]
  },
  {
   "title": "Pushing Force- OPCUA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (a.compound->>'@value')::INTEGER AS \"Pushing Force\", a.ts AS Time\r\nFROM attributes a\r\nwhere  a.id like '%/PushingForce'"
    }
   ]
  },
  {
   "title": "Alarm4 - OPCUA",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (compound ->>'@value')::INTEGER AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Compound' and a.id like '%Alarm4'"
    }
   ]
  },
  {
   "title": "Alarm2 - OPCUA",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (compound ->>'@value')::INTEGER AS Alarm2, a.ts as Time\r\nFROM attributes a\r\nwhere a.\"valuetype\"='Compound' and a.id like '%Alarm2'"
    }
   ]
  }
 ]
}