{
 "title": "OPCUA _Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SETON",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT a.\"boolean\" AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Boolean' and a.id like '%/SETON'"
    }
   ]
  },
  {
   "title": "AREA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT a.\"boolean\" AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Boolean' and a.id like '%/AREA'"
    }
   ]
  },
  {
   "title": "Alarm4",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (compound ->>'@value')::INTEGER AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Compound' and a.id like '%Alarm4'"
    }
   ]
  },
  {
   "title": "Alarm2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT (compound ->>'@value')::INTEGER AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Compound' and a.id like '%Alarm2'"
    }
   ]
  },
  {
   "title": "BUSY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT a.\"boolean\" AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Boolean' and a.id like '%/BUSY'"
    }
   ]
  },
  {
   "title": "StepDataOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT a.\"boolean\" AS value, a.ts \r\nFROM attributes a\r\nwhere a.\"valuetype\"='Boolean' and a.id like '%/WAREA'"
    }
   ]
  }
 ]
}