{
 "title": "TurtleDashboard_ARISE",
 "time": { "from": "2024-11-29T10:56:35.583Z", "to": "2024-11-29T10:58:56.225Z" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Turtle  1 - Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.x')as REAL) AS \"Pose X\",\nCAST(jsonb_path_query(compound,'$.y') as REAL) AS \"Pose Y\",\nCAST(jsonb_path_query(compound,'$.theta') as REAL)as \"Pose Theta\",\nCAST(jsonb_path_query(compound,'$.linear_velocity') as REAL ) as \"Pose Linear Velocity\",\nCAST(jsonb_path_query(compound,'$.angular_velocity') as REAL ) as \"Pose Angular velocity\", \na.ts FROM public.\"attributes\" AS a where a.id like '%pose'and   compound->>'turtle_id' = '1';\n"
    }
   ]
  },
  {
   "title": "Turtle 1- Velocity Linear ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \nCAST(a.compound->'linear'->>'x' as INTEGER) as \"Velocity Linear X\",\nCAST(a.compound->'linear'->>'y' as INTEGER) as \"Velocity Linear Y\",\nCAST(a.compound->'linear'->>'z' as INTEGER)as \"Velocity Linear Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '1';"
    }
   ]
  },
  {
   "title": "Turtle 1 -Velocity Angular ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select \nCAST(a.compound->'angular'->>'x' as INTEGER)as \"Velocity Angular X\",\nCAST(a.compound->'angular'->>'y' as INTEGER)as \"Velocity Angular Y\",\nCAST(a.compound->'angular'->>'z' as INTEGER)as \"Velocity Angular Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '1';\n"
    }
   ]
  },
  {
   "title": "Turtle 2 - Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.x')as REAL) AS \"Pose X\",\nCAST(jsonb_path_query(compound,'$.y') as REAL) AS \"Pose Y\",\nCAST(jsonb_path_query(compound,'$.theta') as REAL)as \"Pose Theta\",\nCAST(jsonb_path_query(compound,'$.linear_velocity') as REAL ) as \"Pose Linear Velocity\",\nCAST(jsonb_path_query(compound,'$.angular_velocity') as REAL ) as \"Pose Angular velocity\", \na.ts FROM public.\"attributes\" AS a where a.id like '%pose'and   compound->>'turtle_id' = '2';\n"
    }
   ]
  },
  {
   "title": "Turtle 2 -Velocity Linear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \nCAST(a.compound->'linear'->>'x' as INTEGER) as \"Velocity Linear X\",\nCAST(a.compound->'linear'->>'y' as INTEGER) as \"Velocity Linear Y\",\nCAST(a.compound->'linear'->>'z' as INTEGER)as \"Velocity Linear Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '2';"
    }
   ]
  },
  {
   "title": "Turtle 2 - Velocity Angular ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "select \nCAST(a.compound->'angular'->>'x' as INTEGER)as \"Velocity Angular X\",\nCAST(a.compound->'angular'->>'y' as INTEGER)as \"Velocity Angular Y\",\nCAST(a.compound->'angular'->>'z' as INTEGER)as \"Velocity Angular Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '2';\n"
    }
   ]
  },
  {
   "title": "Turtle 3- Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.x')as REAL) AS \"Pose X\",\nCAST(jsonb_path_query(compound,'$.y') as REAL) AS \"Pose Y\",\nCAST(jsonb_path_query(compound,'$.theta') as REAL)as \"Pose Theta\",\nCAST(jsonb_path_query(compound,'$.linear_velocity') as REAL ) as \"Pose Linear Velocity\",\nCAST(jsonb_path_query(compound,'$.angular_velocity') as REAL ) as \"Pose Angular velocity\", \na.ts FROM public.\"attributes\" AS a where a.id like '%pose'and   compound->>'turtle_id' = '3';\n"
    }
   ]
  },
  {
   "title": "Turtle 3 - Velocity Linear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \nCAST(a.compound->'linear'->>'x' as INTEGER) as \"Velocity Linear X\",\nCAST(a.compound->'linear'->>'y' as INTEGER) as \"Velocity Linear Y\",\nCAST(a.compound->'linear'->>'z' as INTEGER)as \"Velocity Linear Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '3';"
    }
   ]
  },
  {
   "title": "Turtle 3 - Velocity Angular  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "select \nCAST(a.compound->'angular'->>'x' as INTEGER)as \"Velocity Angular X\",\nCAST(a.compound->'angular'->>'y' as INTEGER)as \"Velocity Angular Y\",\nCAST(a.compound->'angular'->>'z' as INTEGER)as \"Velocity Angular Z\",\na.ts FROM public.\"attributes\" AS a where a.id like '%velocityCommand' and compound->>'turtle_id' = '3';\n"
    }
   ]
  }
 ]
}