{
 "title": "TurtleDashboard_ARISE",
 "time": { "from": "2024-11-29T10:56:35.583Z", "to": "2024-11-29T10:58:56.225Z" },
 "panels": [
  {
   "title": "Turtle  1 - Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_index,pose['linear_velocity'] as \"Velocity Linear Pose\",pose['x'] as \"Pose x\",pose['y'] as \"Pose y\",pose['theta'] as \"Pose theta\",pose['angular_velocity'] as \"Pose Angular Velocity\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=1 "
    }
   ]
  },
  {
   "title": "Turtle 1- Velocity Linear ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['linear']['x'] as \"Velocity Linear X\", velocitycommand['linear']['y'] as \"Velocity Linear Y\", velocitycommand['linear']['z'] as \"Velocity Linear Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=1"
    }
   ]
  },
  {
   "title": "Turtle 1 -Velocity Angular ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['angular']['x'] as \"Velocity Angular X\", velocitycommand['angular']['y'] as \"Velocity Angular Y\", velocitycommand['angular']['z'] as \"Velocity Angular Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=1"
    }
   ]
  },
  {
   "title": "Turtle 2 - Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_index,pose['linear_velocity'] as \"Velocity Linear Pose\",pose['x'] as \"Pose x\",pose['y'] as \"Pose y\",pose['theta'] as \"Pose theta\",pose['angular_velocity'] as \"Pose Angular Velocity\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=2 "
    }
   ]
  },
  {
   "title": "Turtle 2 -Velocity Linear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['linear']['x'] as \"Velocity Linear X\", velocitycommand['linear']['y'] as \"Velocity Linear Y\", velocitycommand['linear']['z'] as \"Velocity Linear Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=2"
    }
   ]
  },
  {
   "title": "Turtle 2 - Velocity Angular ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['linear']['x'] as \"Velocity Linear X\", velocitycommand['linear']['y'] as \"Velocity Linear Y\", velocitycommand['linear']['z'] as \"Velocity Linear Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=2 "
    }
   ]
  },
  {
   "title": "Turtle 3- Pose",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time_index,pose['linear_velocity'] as \"Velocity Linear Pose\",pose['x'] as \"Pose x\",pose['y'] as \"Pose y\",pose['theta'] as \"Pose theta\",pose['angular_velocity'] as \"Pose Angular Velocity\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=3 "
    }
   ]
  },
  {
   "title": "Turtle 3 - Velocity Linear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['linear']['x'] as \"Velocity Linear X\", velocitycommand['linear']['y'] as \"Velocity Linear Y\", velocitycommand['linear']['z'] as \"Velocity Linear Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=3"
    }
   ]
  },
  {
   "title": "Turtle 3 - Velocity Angular  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time_index,velocitycommand['linear']['x'] as \"Velocity Linear X\", velocitycommand['linear']['y'] as \"Velocity Linear Y\", velocitycommand['linear']['z'] as \"Velocity Linear Z\"\nFROM \"doc\".\"etrobot\" \nWHERE velocitycommand['turtle_id']=3 "
    }
   ]
  }
 ]
}